name: Makefile CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      
    - name: Install build dependencies
      run: sudo apt-get install -qq -y build-essential g++ gcc-multilib g++-multilib

    - name: Setup Intel Repository
      run: |
        wget https://apt.repos.intel.com/intel-gpg-keys/GPG-PUB-KEY-INTEL-SW-PRODUCTS.PUB
        sudo apt-key add GPG-PUB-KEY-INTEL-SW-PRODUCTS.PUB
        rm GPG-PUB-KEY-INTEL-SW-PRODUCTS.PUB
        sudo echo "deb https://apt.repos.intel.com/oneapi all main" | sudo tee /etc/apt/sources.list.d/oneAPI.list
        sudo apt-get update

    - name: Install Intel One API
      run: |
        sudo apt-get install -y intel-oneapi-common-vars
        sudo apt-get install -y intel-oneapi-compiler-fortran
        sudo apt-get install -y intel-oneapi-mkl
        sudo apt-get install -y intel-oneapi-mpi
        sudo apt-get install -y intel-oneapi-mpi-devel

    - name: Run build
      working-directory: ./PugMod
      run: make
    
    - name: Move files
      run: |
        mkdir -p publish/addons/pugmod/dlls
        mv ./PugMod/Release/pugmod_mm.so publish/addons/pugmod/dlls
        cp -ar cstrike/. publish

    - name: Deploy artifacts
      uses: actions/upload-artifact@v2
      with:
        name: linux
        path: publish/*